# general settings
name: AGDN_X3_L1_1000k
model_type: SRModel
scale: 3
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: ../datasets/train/DF2K_train_HR_sub.lmdb
    dataroot_lq: ../datasets/train/DF2K_train_LR_X3_sub.lmdb
    io_backend:
      type: lmdb

    gt_size: 144
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 16
    batch_size_per_gpu: 64
    dataset_enlarge_ratio: 10
    prefetch_mode: ~

  val:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: ../datasets/test/HR/Set5/x3
    dataroot_lq: ../datasets/test/LRBI/Set5/x3
    io_backend:
      type: disk

# network structures
network_g:
  type: AGDN
  num_feat: 42
  upscale: 3

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-3
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [100000, 500000, 800000, 900000, 950000]
    gamma: 0.5

  total_iter: 1000000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 3
      test_y_channel: true

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
